language: R
sudo: false
cache: packages

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e "packagedocs::deploy_travis()"

env:
  global:
    secure: o9xvHNCD5Hmb5pw+wiWkWsCxaVb4l6tPJIz6QvQ5HsYAp/c/vP85lSgNq+EQ1wESAOEpclhxhaiJml6ePdzwHslElDHa9hG3OGUaynS1sinpkrBKy2TxDSuLKkgCnuPQO9z7G2vS1ob6uQJkqeExc4YZxCByVYHjucg/mJuMgVyMGoFBMWmDhAB7h+GnRTMBygLl7JmLQug8MQpDmUxKbKUuyFEGTYrvsxB6TrJGFBa42SVebO+os+jfbAEivFNVB4kKe1hwcl3yjsztguJE7d7A2L9s1NYJwEOPIWlhzkMzwTppDD5m79baC2wS8PDq8vvEZWG4Guqq91twZnMDnEKpVUIuD6hGbm+988IYjWCeTtugRHTd91lv4Mi9SiIzMKjbFuCGaNb4/QQwfKA7QfG73GJkUhPx91eM1vLiYVZ4/smQUi/ReuEI7GuhaRdAWP/9kofXQJEzPHPCK/By5wF63T7gV0i2ESLabqUHZZAbyG4ndZ/EuuXAmgUk6IQWJ8k10jJORpJFOOZKpPooIbZVDgW1hqTqK4p9Y4NDZhVCt1iYPUGZ/PV6f06/Zl3bqWi8fEWFgTzLD2nHglPfWwzsdndqusq+3NUrBqO5UyFxw8JoPy2G+lbvIwbJkb8HFDX7vf2Q2JUnYRbdrqdghyXrHZi3H4Tiqb9s8eUIyr8=
