
language: R
sudo: false
cache: packages

r_github_packages:
  - schloerke/travisDrat

after_success:
  - Rscript -e "covr::codecov()"
  - Rscript -e "packagedocs::deploy_travis()"
  - Rscript -e "travisDrat::deploy_drat(repo = 'schloerke/drat', valid_branches = 'master')"

env:
  global:
  - secure: o9xvHNCD5Hmb5pw+wiWkWsCxaVb4l6tPJIz6QvQ5HsYAp/c/vP85lSgNq+EQ1wESAOEpclhxhaiJml6ePdzwHslElDHa9hG3OGUaynS1sinpkrBKy2TxDSuLKkgCnuPQO9z7G2vS1ob6uQJkqeExc4YZxCByVYHjucg/mJuMgVyMGoFBMWmDhAB7h+GnRTMBygLl7JmLQug8MQpDmUxKbKUuyFEGTYrvsxB6TrJGFBa42SVebO+os+jfbAEivFNVB4kKe1hwcl3yjsztguJE7d7A2L9s1NYJwEOPIWlhzkMzwTppDD5m79baC2wS8PDq8vvEZWG4Guqq91twZnMDnEKpVUIuD6hGbm+988IYjWCeTtugRHTd91lv4Mi9SiIzMKjbFuCGaNb4/QQwfKA7QfG73GJkUhPx91eM1vLiYVZ4/smQUi/ReuEI7GuhaRdAWP/9kofXQJEzPHPCK/By5wF63T7gV0i2ESLabqUHZZAbyG4ndZ/EuuXAmgUk6IQWJ8k10jJORpJFOOZKpPooIbZVDgW1hqTqK4p9Y4NDZhVCt1iYPUGZ/PV6f06/Zl3bqWi8fEWFgTzLD2nHglPfWwzsdndqusq+3NUrBqO5UyFxw8JoPy2G+lbvIwbJkb8HFDX7vf2Q2JUnYRbdrqdghyXrHZi3H4Tiqb9s8eUIyr8=
  - secure: k3WT/jgT0Hj/ZLk5oXAH4UOZWWBebAC1hTsKv6aq63pfBMxzFnhub4TOzai+H4s0X2Nafq6G/eXJhu3liyNBA2FYuZQ5Fat3Vwf6fnKPsslh3hsyeIfSoUweghtfqGY229Q7LETacDu7lSSzshboK7FkEbT2u0A/XqaM/E9OuLjATjhs8C6GhrV6O/FXd2Xos5zOqLkdi75Zm4XN8i/u9D4DxatLZdHmGa4TXTTWJvEIBL6O22+WRDuQLmLqeUV+tpkLCcyPnMOKtIxJQVYBEyIAIuPcI/k9FqAPQQUbRsY5WZmXGSydhwFU8+wHHi65A3AFo/Nh/QhV4jrIFSev41Fm5dXCBprDGpYQEaypdVXNC8Fu7s9lSrucrNXZxNoETeVdh584MHsW7e6XzAFNyEIbscoV6jfLMZK25SBYW7isKhpKGTMJiTV1l5+VCUyrEBTa0HfxWx2wj9ZnDzpkST+IGjPl7dguDGmsZeSnvWNRN5jIsQn9ecx7WV+lXJxmiNu2um0bF2Prcm8EpyjdBBd/UyF396WOwZ5SSAm+mBnlcshhF/+WyynI9+BKuaGVU7p8WJIkKqiBmN0big/1f4B7vg86C2vXi7Rq4vjGq/KJnn4+Yvy4pWuGIq0Gwl7ojqNZ8Q7uYN5LzQGcbht0NnX5/vmspAYSke/BdZeOhAk=

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
    - dev
    - travis
